// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWUvYG9oS8FfgqkufAh8RuB8XtiBWy5g',
    appId: '1:380595799896:web:d5e977cf2d790e878b872d',
    messagingSenderId: '380595799896',
    projectId: 'skillnest-9906e',
    authDomain: 'skillnest-9906e.firebaseapp.com',
    storageBucket: 'skillnest-9906e.firebasestorage.app',
    measurementId: 'G-9N9C2CDJ0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7Wkg7z-5joLzPiuPvVaup0Nd0cWDQO0',
    appId: '1:380595799896:android:6b529275ffb7de8d8b872d',
    messagingSenderId: '380595799896',
    projectId: 'skillnest-9906e',
    storageBucket: 'skillnest-9906e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfqh3LQS9yGBb590eXkT_oSn7SsxVC9I',
    appId: '1:380595799896:ios:0b95bcb7a3e8af7f8b872d',
    messagingSenderId: '380595799896',
    projectId: 'skillnest-9906e',
    storageBucket: 'skillnest-9906e.firebasestorage.app',
    iosBundleId: 'com.example.skillnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcfqh3LQS9yGBb590eXkT_oSn7SsxVC9I',
    appId: '1:380595799896:ios:0b95bcb7a3e8af7f8b872d',
    messagingSenderId: '380595799896',
    projectId: 'skillnest-9906e',
    storageBucket: 'skillnest-9906e.firebasestorage.app',
    iosBundleId: 'com.example.skillnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWUvYG9oS8FfgqkufAh8RuB8XtiBWy5g',
    appId: '1:380595799896:web:0a4f410e41494b558b872d',
    messagingSenderId: '380595799896',
    projectId: 'skillnest-9906e',
    authDomain: 'skillnest-9906e.firebaseapp.com',
    storageBucket: 'skillnest-9906e.firebasestorage.app',
    measurementId: 'G-S8EC7ZTLPN',
  );
}
